-- Create classification table
CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_name CHARACTER VARYING NOT NULL UNIQUE
);

-- Insert some sample data
INSERT INTO public.classification (classification_name)
VALUES 
  ('Custom'),
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedan')
ON CONFLICT DO NOTHING; 